### ISSUE TITLE
梯度结果不对

### ISSUE THREAD

**Issue by demerzel-iv** [demerzel-iv/bmtrain_mindspore#1]
先按照readme改一下ms.common.parameter
运行命令`bash run.sh 8`
期望得到梯度为28，但是输出梯度为0

**Comment by ZOULQ** [comment]
$ bash run.sh 4
-----rank-3, [(Tensor(shape=[], dtype=Float32, value= 12), (Tensor(shape=[3], dtype=Float32, value= [ 6.00000000e+00,  6.00000000e+00,  6.00000000e+00]),))]------
-----rank-0, [(Tensor(shape=[], dtype=Float32, value= 12), (Tensor(shape=[3], dtype=Float32, value= [ 6.00000000e+00,  6.00000000e+00,  6.00000000e+00]),))]------
-----rank-2, [(Tensor(shape=[], dtype=Float32, value= 12), (Tensor(shape=[3], dtype=Float32, value= [ 6.00000000e+00,  6.00000000e+00,  6.00000000e+00]),))]------
-----rank-1, [(Tensor(shape=[], dtype=Float32, value= 12), (Tensor(shape=[3], dtype=Float32, value= [ 6.00000000e+00,  6.00000000e+00,  6.00000000e+00]),))]------

本地环境验证结果如上，非0。建议采用下面方式调试：
1. 在parameter切分前后加print打印，看正向通信结果是否符合预期；
2. 通过ms.set_context(mode=ms.PYNATIVE_MODE, save_graphs=True,  save_graphs_path="ir")保存反向IR图，在ir文件夹下查看launch_bprop_graph_xxx.ir文件，查看反向图算子是否正确，AllGather算子反向算子对应ReduceScatter，可参考：

subgraph @kernel_graph0() {
  %0(CNode_23) = PrimFunc_OnesLike(Tensor(shape=[], dtype=Float32, value=<uninitialized>))
      : (<Tensor[Float32], ()>) -> (<Tensor[Float32], ()>)
      # Scope: (Default)
  %1(CNode_24) = PrimFunc_Reshape(%0, (I64(1), I64(1)))
      : (<Tensor[Float32], ()>, <Tuple[Int64*2], TupleShape(NoShape, NoShape)>) -> (<Tensor[Float32], (1, 1)>)
      # Scope: (Bprop/gradReduceSum)
  %2(CNode_25) = PrimFunc_Tile(%1, (I64(3), I64(4))) cnode_attrs: {convert_attr_node: Bool(1)}
      : (<Tensor[Float32], (1, 1)>, <Tuple[Int64*2], TupleShape(NoShape, NoShape)>) -> (<Tensor[Float32], (3, 4)>)
      # Scope: (Bprop/gradReduceSum)
  %3(CNode_26) = PrimFunc_Mul(%para1_Parameter_28, %2) cnode_attrs: {convert_attr_node: Bool(1)}
      : (<Tensor[Float32], ()>, <Tensor[Float32], (3, 4)>) -> (<Tensor[Float32], (3, 4)>)
      # Scope: (Bprop/gradMul)
  %4(CNode_29) = PrimFunc_Reshape(%3, (I64(12)))
      : (<Tensor[Float32], (3, 4)>, <Tuple[Int64], TupleShape(NoShape)>) -> (<Tensor[Float32], (12)>)
      # Scope: (Bprop/gradReshape)
  %5(CNode_30) = StridedSliceGrad(%4, (I64(12)), (I64(0)), (I64(12)), (I64(1))) primitive_attrs: {new_axis_mask: I64(0), shrink_axis_mask: I64(0), end_mask: I64(0), input_names: (dy, shapex, begin, end, strides), output_names: (output), begin_mask: I64(0), ellipsis_mask: I64(0)}
      : (<Tensor[Float32], (12)>, <Tuple[Int64], TupleShape(NoShape)>, <Tuple[Int64], TupleShape(NoShape)>, <Tuple[Int64], TupleShape(NoShape)>, <Tuple[Int64], TupleShape(NoShape)>) -> (<Tensor[Float32], (12)>)
      # Scope: (Bprop/gradStridedSlice)
  %6(CNode_31) = ReduceScatter(%5) {instance name: grad} primitive_attrs: {group: "hccl_world_group", input_names: (input_x), fusion: I64(0), op: "sum", output_names: (output), rank_size: I64(2), no_eliminate: Bool(1)}
      : (<Tensor[Float32], (12)>) -> (<Tensor[Float32], (6)>)
      # Scope: (Bprop/gradAllGather)
  %7(CNode_32) = MakeTuple(%6)
      : (<Tensor[Float32], (6)>) -> (<Tuple[Tensor[Float32]], TupleShape((6))>)
      # Scope: (Default)
  Return(%7) primitive_attrs: {visited: Bool(1)}
      : (<Tuple[Tensor[Float32]], TupleShape((6))>)
      # Scope: (Default)
}

3. 另外代码建议(理论上不影响上述问题结果)：
1). test.py 用例结束后调用mindspore.communication.release()释放资源；
2). grad_fn = ms.grad(m.construct, weights=m.trainable_params(), grad_position=0)： m.construct->m； 如果不需要对input求导，可以设置grad_position=None;
3). 可以使用msrun代替mpirun：
    msrun  --worker_num ${n_works}   --local_worker_num ${n_works}  --log_dir=msrun_log  test.py
