### ISSUE TITLE
动态内存分配问题

### ISSUE THREAD

**Issue by lvyufeng** [demerzel-iv/bmtrain_mindspore#3]
临时解决方法：
设置环境变量（此环境变量正式版会改）：
MS_DEV_ENABLE_ASCEND_VMM=1
MS_DEV_ASCEND_VMM_ALIGN_SIZE="2MB"

使用限制：
1. 可能导致第一个step时间变长
2. 不支持GE（动态图不涉及）
3. 碎片整理时可能会影响执行性能

**Comment by lvyufeng** [comment]
export MS_DEV_ALLOC_CONF=enable_vmm:True,vmm_align_size:2MB

**Comment by lvyufeng** [comment]
最新master的环境变量配置：

export MS_ALLOC_CONF=enable_vmm:True,vmm_align_size:2MB

**Comment by demerzel-iv** [comment]
<img width="498" alt="图片" src="https://github.com/demerzel-iv/bmtrain_mindspore/assets/47804758/2fb5ebfe-5b46-4bde-9a35-05a946ab8791">

三个设置都试了一下，好像npu-smi info还是不能显示准确的显存占用
