### ISSUE TITLE
关于StubTensor

### ISSUE THREAD

**Issue by demerzel-iv** [demerzel-iv/bmtrain_mindspore#5]
<img width="660" alt="图片" src="https://github.com/demerzel-iv/bmtrain_mindspore/assets/47804758/44ee56b9-c435-4cb5-9a6d-0ef3478ede85">

StubTensor和普通的Tensor有什么区别

**Comment by lvyufeng** [comment]
可以理解为是Tensor的一个壳，因为MindSpore没做Pytorch的存储分离设计，导致创建Tensor非常慢，影响动态图性能，所以为了加速，搞了一层壳，然后又通过这层壳做了算子异步下发。

StubTensor和Tensor的类方法都是一样的，所以可以照常写。
