### ISSUE TITLE
[Question] 流量监测

### ISSUE THREAD

**Issue by demerzel-iv** [demerzel-iv/bmtrain_mindspore#6]
是否有方法监控程序运行时host和device之间（即cpu和ascend卡之间），以及device和device之间，的通信流量情况

**Comment by zangqx-2024** [comment]
mindspore profiler 工具能采集到device到device之前的通信量，初始化的参数加上profile_communication=True; 采集的数据通过MindInsight查看，或者直接查看hccl_raw_xx.csv文件
